name: Deploy Lambdas
on:
  push:
    branches: 
     - main
  workflow_call:

env:
  ARTIFACT_BUCKET: "raw-iot-final-data-edu-22"

jobs:      
  deploy-input-iot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ORG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ORG }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_ORG }}
          aws-region: ${{ secrets.AWS_REGION_ORG }}

      - name: zip code
        run: |
          zip -r input-iot-data.zip input-iot-data/

      - name: upload artifact
        run: |
          aws s3 cp input-iot-data.zip s3://${{env.ARTIFACT_BUCKET}}/artifacts/input.zip

      - name: deploy
        run: |
          cd input-iot-data
          aws cloudformation deploy --stack-name input-iot-stack --template-file input-iot-data/cloudformation.yaml
    
